-- 설치 정책의 단일 원본. 업데이트는 bootstrap + doctor + smoke 검증과 함께 한다.
local root = vim.fs.dirname(vim.fs.dirname(vim.fs.dirname(debug.getinfo(1, "S").source:sub(2))))
return {
  neovim = vim.trim(table.concat(vim.fn.readfile(root .. "/.nvim-version"))),
  treesitter_cli = "0.26.11",
  typescript = "6.0.3",
  servers = { "lua_ls", "ts_ls", "gopls", "basedpyright", "ruff", "eslint" },
  mason = {
    ["lua-language-server"] = "3.18.2",
    ["typescript-language-server"] = "5.3.0",
    ["gopls"] = "v0.22.0",
    ["goimports"] = "v0.45.0",
    ["basedpyright"] = "1.39.6",
    ["ruff"] = "0.15.20",
    ["eslint-lsp"] = "4.10.0",
    ["prettier"] = "3.8.3",
    ["stylua"] = "v2.5.2",
  },
  java = {
    jdtls = { version = "1.54.0" },
    lombok = { version = "1.18.42" },
    java_test = { version = "0.43.2" },
    java_debug_adapter = { version = "0.58.3" },
    spring_boot_tools = { version = "1.55.1" },
    jdk = { version = "25.0.3" },
  },
  parsers = {
    "lua",
    "vim",
    "vimdoc",
    "query",
    "go",
    "gomod",
    "gosum",
    "rust",
    "python",
    "typescript",
    "javascript",
    "tsx",
    "json",
    "yaml",
    "toml",
    "html",
    "css",
    "markdown",
    "markdown_inline",
    "bash",
    "gitignore",
    "sql",
    "regex",
    "java",
    "properties",
    "xml",
  },
}
